apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-backend
  namespace: heena
  labels:
    app: chatgpt-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatgpt-backend
  template:
    metadata:
      labels:
        app: chatgpt-backend
    spec:
      containers:
      - name: backend
        image: ollama/ollama
        ports:
        - containerPort: 11434
        lifecycle:
          postStart:
            exec:
              command:
               - /bin/sh
               - -c
               - "ollama run llama3.2:1b"
          
