apiVersion: v1
kind: Service
metadata:
  name: chatgpt-backend-svc
  namespace: heena
spec:
  selector:
    app: chatgpt-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 11434
  type: ClusterIP