apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-frontend
  labels:
    app: chatgpt-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatgpt-frontend
  template:
    metadata:
      labels:
        app: chatgpt-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/open-webui/open-webui:main # Replace with your image
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: OLLAMA_BASE_URL
          value: "http://10.0.231.220"
        