apiVersion: v1
kind: Service
metadata:
  name: chatgpt-frontend-svc
  namespace: heena
spec:
  selector:
    app: chatgpt-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
